/* SPDX-License-Identifier: BSD-2-Clause */
//[File]            : cb_ckgen_top.h
//[Revision time]   : Tue May  2 10:36:42 2023
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2023 Mediatek Incorportion. All rights reserved.

#ifndef __CB_CKGEN_TOP_REGS_H__
#define __CB_CKGEN_TOP_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CB_CKGEN_TOP CR Definitions                     
//
//****************************************************************************

#define CB_CKGEN_TOP_BASE                                      0x70000000

#define CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR                         (CB_CKGEN_TOP_BASE + 0x100) // 0100
#define CB_CKGEN_TOP_CBTOP_CKGEN1_ADDR                         (CB_CKGEN_TOP_BASE + 0X104) // 0104
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_ADDR                       (CB_CKGEN_TOP_BASE + 0x110) // 0110
#define CB_CKGEN_TOP_CBTOP_CKGEN_DUMMY_ADDR                    (CB_CKGEN_TOP_BASE + 0x120) // 0120
#define CB_CKGEN_TOP_CBTOP_RSV_ADDR                            (CB_CKGEN_TOP_BASE + 0x130) // 0130
#define CB_CKGEN_TOP_CBTOP_CKGEN5_ADDR                         (CB_CKGEN_TOP_BASE + 0x148) // 0148
#define CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR                         (CB_CKGEN_TOP_BASE + 0x14C) // 014C
#define CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR                         (CB_CKGEN_TOP_BASE + 0x150) // 0150
#define CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR                         (CB_CKGEN_TOP_BASE + 0x154) // 0154
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR                       (CB_CKGEN_TOP_BASE + 0x240) // 0240
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR                       (CB_CKGEN_TOP_BASE + 0x244) // 0244
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR                       (CB_CKGEN_TOP_BASE + 0x248) // 0248
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR                       (CB_CKGEN_TOP_BASE + 0x24C) // 024C
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_ADDR                       (CB_CKGEN_TOP_BASE + 0x250) // 0250
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_ADDR                   (CB_CKGEN_TOP_BASE + 0x254) // 0254
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_ADDR                   (CB_CKGEN_TOP_BASE + 0x258) // 0258
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_2_ADDR                   (CB_CKGEN_TOP_BASE + 0x25C) // 025C
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_3_ADDR                   (CB_CKGEN_TOP_BASE + 0x260) // 0260




/* =====================================================================================

  ---CBTOP_CKGEN0 (0x70000000 + 0x100)---

    RESERVED0[17..0]             - (RO) Reserved bits
    PMU_32k_DIV_SEL_SW[18]       - (RW) Int 32k xtal divider selection switch
                                     0: XTAL divider ratio is HW mapping by XTAL_FREQ[10:0]
                                       [10]: XTAL=52  MHz ,11'd1586, 52   MHz/1587=32.766..KHz
                                       [9] : XTAL=40   MHz ,11'd1220, 40   MHz/1221=32.760..KHz
                                       [8] : XTAL=38.4MHz ,11'd1170, 38.4MHz/1171=32.792..KHz
                                       [6] : XTAL=26   MHz ,11'd  793, 26   MHz/  794=32.745..KHz
                                       [5] : XTAL=24   MHz ,11'd  732, 24   MHz/  733=32.742..KHz
                                       [4] : XTAL=20   MHz ,11'd  610, 20   MHz/  611=32.733..KHz
                                       [3] : XTAL=19.2MHz ,11'd  585, 19.2MHz/  586=32.764..KHZ
                                     1: XTAL divider ratio from 32K_DIV_SEL[10:0]
    PMU_32k_DIV_EN[19]           - (RW) Int 32k xtal divider enable switch
                                     0: divider disable
                                     1: divider enable
    RESERVED20[20]               - (RO) Reserved bits
    PMU_32k_DIV_SEL[31..21]      - (RW) Divider for Int 32k
                                     clk div is set to N, the divided clock is xtal clock/ (N+1).
                                     Default : 26MHz/(793+1) = 32.745..KHz

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_ADDR         CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_MASK         0xFFE00000                // PMU_32k_DIV_SEL[31..21]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SHFT         21
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_ADDR          CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_MASK          0x00080000                // PMU_32k_DIV_EN[19]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_EN_SHFT          19
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN0_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_MASK      0x00040000                // PMU_32k_DIV_SEL_SW[18]
#define CB_CKGEN_TOP_CBTOP_CKGEN0_PMU_32k_DIV_SEL_SW_SHFT      18

/* =====================================================================================

  ---CBTOP_CKGEN1 (0x70000000 + 0X104)---

    connsys_ap_hclk_ck_sel[1..0] - (RW) connsys ap_hclk_ck sel
                                     2'b11: wpll 160M
                                     2'b10: ulposc 156M
                                     2'b01: ulposc 52M
                                     2'b00: crystal clock 52/40M
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN1_connsys_ap_hclk_ck_sel_ADDR  CB_CKGEN_TOP_CBTOP_CKGEN1_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN1_connsys_ap_hclk_ck_sel_MASK  0x00000003                // connsys_ap_hclk_ck_sel[1..0]
#define CB_CKGEN_TOP_CBTOP_CKGEN1_connsys_ap_hclk_ck_sel_SHFT  0

/* =====================================================================================

  ---CBTOP_PWRCTLCR (0x70000000 + 0x110)---

    XTAL_FREQ[10..0]             - (RW) Should set as 1 hot
                                     [10] : XTAL=52MHz
                                     [9] :   XTAL=40MHz
                                     [8] :   XTAL=38.4MHz
                                     [6] :   XTAL=26MHz (default)
                                     [5] :   XTAL=24MHz
                                     [4] :   XTAL=20MHz
                                     [3] :   XTAL=19.2MHz
                                     [2] :   XTAL=25MHz
    RESERVED11[31..11]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_ADDR             CB_CKGEN_TOP_CBTOP_PWRCTLCR_ADDR
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_MASK             0x000007FF                // XTAL_FREQ[10..0]
#define CB_CKGEN_TOP_CBTOP_PWRCTLCR_XTAL_FREQ_SHFT             0

/* =====================================================================================

  ---CBTOP_CKGEN_DUMMY (0x70000000 + 0x120)---

    cr_ckgen_dummy[31..0]        - (RW) Dummy register

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN_DUMMY_cr_ckgen_dummy_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN_DUMMY_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN_DUMMY_cr_ckgen_dummy_MASK     0xFFFFFFFF                // cr_ckgen_dummy[31..0]
#define CB_CKGEN_TOP_CBTOP_CKGEN_DUMMY_cr_ckgen_dummy_SHFT     0

/* =====================================================================================

  ---CBTOP_RSV (0x70000000 + 0x130)---

    sdio_wrapper_ck_bt_req[0]    - (RW)  xxx 
    sdio_wrapper_ck_wf_req[1]    - (RW)  xxx 
    cr_reserved_A[3..2]          - (RW)  xxx 
    force_adie_xtal_ready[4]     - (RW) force Adie xtal on @low power mode
    cr_reserved_B[13..5]         - (RW)  xxx 
    d_polling_timeout_flag[14]   - (RW) polling d die timeout flag(SE used)
    a_polling_timeout_flag[15]   - (RW) polling a die timeout flag(SE used)
    cr_reserved_1[31..16]        - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_ADDR              CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_MASK              0xFFFF0000                // cr_reserved_1[31..16]
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_1_SHFT              16
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_MASK     0x00008000                // a_polling_timeout_flag[15]
#define CB_CKGEN_TOP_CBTOP_RSV_a_polling_timeout_flag_SHFT     15
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_MASK     0x00004000                // d_polling_timeout_flag[14]
#define CB_CKGEN_TOP_CBTOP_RSV_d_polling_timeout_flag_SHFT     14
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_B_ADDR              CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_B_MASK              0x00003FE0                // cr_reserved_B[13..5]
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_B_SHFT              5
#define CB_CKGEN_TOP_CBTOP_RSV_force_adie_xtal_ready_ADDR      CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_force_adie_xtal_ready_MASK      0x00000010                // force_adie_xtal_ready[4]
#define CB_CKGEN_TOP_CBTOP_RSV_force_adie_xtal_ready_SHFT      4
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_A_ADDR              CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_A_MASK              0x0000000C                // cr_reserved_A[3..2]
#define CB_CKGEN_TOP_CBTOP_RSV_cr_reserved_A_SHFT              2
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_MASK     0x00000002                // sdio_wrapper_ck_wf_req[1]
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_wf_req_SHFT     1
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_ADDR     CB_CKGEN_TOP_CBTOP_RSV_ADDR
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_MASK     0x00000001                // sdio_wrapper_ck_bt_req[0]
#define CB_CKGEN_TOP_CBTOP_RSV_sdio_wrapper_ck_bt_req_SHFT     0

/* =====================================================================================

  ---CBTOP_CKGEN5 (0x70000000 + 0x148)---

    pllgp_ref_cken[0]            - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_ADDR          CB_CKGEN_TOP_CBTOP_CKGEN5_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_MASK          0x00000001                // pllgp_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN5_pllgp_ref_cken_SHFT          0

/* =====================================================================================

  ---CBTOP_CKGEN6 (0x70000000 + 0x14C)---

    pcie_phya_ref_cken[0]        - (RW)  xxx 
    pcie_phyd_ref_cken[1]        - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_MASK      0x00000002                // pcie_phyd_ref_cken[1]
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phyd_ref_cken_SHFT      1
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_ADDR      CB_CKGEN_TOP_CBTOP_CKGEN6_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_MASK      0x00000001                // pcie_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN6_pcie_phya_ref_cken_SHFT      0

/* =====================================================================================

  ---CBTOP_CKGEN7 (0x70000000 + 0x150)---

    usb20_phya_ref_cken[0]       - (RW)  xxx 
    usb20_phyd_ref_cken[1]       - (RW)  xxx 
    RESERVED2[31..2]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_MASK     0x00000002                // usb20_phyd_ref_cken[1]
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phyd_ref_cken_SHFT     1
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN7_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_MASK     0x00000001                // usb20_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN7_usb20_phya_ref_cken_SHFT     0

/* =====================================================================================

  ---CBTOP_CKGEN8 (0x70000000 + 0x154)---

    usb30_phya_ref_cken[0]       - (RW)  xxx 
    usb30_phyd_ref_cken[1]       - (RW)  xxx 
    usb30_phyd_osc_ref_cken[2]   - (RW)  xxx 
    usb30_phyd_rosc_ref_cken[3]  - (RW)  xxx 
    RESERVED4[31..4]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_ADDR CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_MASK 0x00000008                // usb30_phyd_rosc_ref_cken[3]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_rosc_ref_cken_SHFT 3
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_ADDR CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_MASK 0x00000004                // usb30_phyd_osc_ref_cken[2]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_osc_ref_cken_SHFT 2
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_MASK     0x00000002                // usb30_phyd_ref_cken[1]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phyd_ref_cken_SHFT     1
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_ADDR     CB_CKGEN_TOP_CBTOP_CKGEN8_ADDR
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_MASK     0x00000001                // usb30_phya_ref_cken[0]
#define CB_CKGEN_TOP_CBTOP_CKGEN8_usb30_phya_ref_cken_SHFT     0

/* =====================================================================================

  ---CBTOP_ULPOSC_0 (0x70000000 + 0x240)---

    rg_osc_rsv1[7..0]            - (RW)  xxx 
    rg_osc_rsv2[15..8]           - (RW)  xxx 
    rg_osc_cali_value[24..16]    - (RW)  xxx 
    RESERVED25[26..25]           - (RO) Reserved bits
    rg_da_osc_en[27]             - (RW)  xxx 
    RESERVED28[30..28]           - (RO) Reserved bits
    rg_da_osc_rst[31]            - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_ADDR         CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_MASK         0x80000000                // rg_da_osc_rst[31]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_rst_SHFT         31
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_MASK          0x08000000                // rg_da_osc_en[27]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_da_osc_en_SHFT          27
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_ADDR     CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_MASK     0x01FF0000                // rg_osc_cali_value[24..16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_cali_value_SHFT     16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_ADDR           CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_MASK           0x0000FF00                // rg_osc_rsv2[15..8]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv2_SHFT           8
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_ADDR           CB_CKGEN_TOP_CBTOP_ULPOSC_0_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_MASK           0x000000FF                // rg_osc_rsv1[7..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_0_rg_osc_rsv1_SHFT           0

/* =====================================================================================

  ---CBTOP_ULPOSC_1 (0x70000000 + 0x244)---

    rg_ckgen_load_cnt[9..0]      - (RW)  xxx 
    rg_freq_offset_value[19..10] - (RW)  xxx 
    rg_abist_meter_sw_en[20]     - (RW)  xxx 
    RESERVED21[23..21]           - (RO) Reserved bits
    rg_ckgen_tri_cal[24]         - (RW)  xxx 
    RESERVED25[27..25]           - (RO) Reserved bits
    rg_mux_sel[31..28]           - (RW)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_ADDR            CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_MASK            0xF0000000                // rg_mux_sel[31..28]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_mux_sel_SHFT            28
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_ADDR      CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_MASK      0x01000000                // rg_ckgen_tri_cal[24]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_tri_cal_SHFT      24
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_ADDR  CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_MASK  0x00100000                // rg_abist_meter_sw_en[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_abist_meter_sw_en_SHFT  20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_ADDR  CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_MASK  0x000FFC00                // rg_freq_offset_value[19..10]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_freq_offset_value_SHFT  10
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_load_cnt_ADDR     CB_CKGEN_TOP_CBTOP_ULPOSC_1_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_load_cnt_MASK     0x000003FF                // rg_ckgen_load_cnt[9..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_1_rg_ckgen_load_cnt_SHFT     0

/* =====================================================================================

  ---CBTOP_ULPOSC_2 (0x70000000 + 0x248)---

    ckgen_cal_cnt[15..0]         - (RO)  xxx 
    ckgen_cal_ok[16]             - (RO)  xxx 
    RESERVED17[19..17]           - (RO) Reserved bits
    ckgen_cal_valid[20]          - (RO)  xxx 
    RESERVED21[21]               - (RO) Reserved bits
    kdone_OSC_CALI[30..22]       - (RO)  xxx 
    ulposc_ready[31]             - (RO)  xxx 

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_MASK          0x80000000                // ulposc_ready[31]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ulposc_ready_SHFT          31
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_ADDR        CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_MASK        0x7FC00000                // kdone_OSC_CALI[30..22]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_kdone_OSC_CALI_SHFT        22
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_ADDR       CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_MASK       0x00100000                // ckgen_cal_valid[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_valid_SHFT       20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_ADDR          CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_MASK          0x00010000                // ckgen_cal_ok[16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_ok_SHFT          16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_ADDR         CB_CKGEN_TOP_CBTOP_ULPOSC_2_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_MASK         0x0000FFFF                // ckgen_cal_cnt[15..0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_2_ckgen_cal_cnt_SHFT         0

/* =====================================================================================

  ---CBTOP_ULPOSC_3 (0x70000000 + 0x24C)---

    topaon_ulposc_52M_rdy[0]     - (RO)  xxx 
    lvts_ulposc_26M_rdy[1]       - (RO)  xxx 
    connsys_ulposc_52M_rdy[2]    - (RO)  xxx 
    connsys_ulposc_156M_rdy[3]   - (RO)  xxx 
    cbinfra_ulposc_26M_rdy[4]    - (RO)  xxx 
    cbinfra_ulposc_52M_rdy[5]    - (RO)  xxx 
    cbinfra_ulposc_156M_rdy[6]   - (RO)  xxx 
    cbinfra_wpll_160M_rdy[7]     - (RO)  xxx 
    spmi_pmif_52M_rdy[8]         - (RO)  xxx 
    RESERVED9[14..9]             - (RO) Reserved bits
    topaon_ulposc_52M_req[15]    - (RO)  xxx 
    lvts_ulposc_26M_req[16]      - (RO)  xxx 
    connsys_ulposc_52M_req[17]   - (RO)  xxx 
    connsys_ulposc_156M_req[18]  - (RO)  xxx 
    cbinfra_ulposc_26M_req[19]   - (RO)  xxx 
    cbinfra_ulposc_52M_req[20]   - (RO)  xxx 
    cbinfra_ulposc_156M_req[21]  - (RO)  xxx 
    cbinfra_wpll_160M_req[22]    - (RO)  xxx 
    RESERVED23[31..23]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_req_MASK 0x00400000                // cbinfra_wpll_160M_req[22]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_req_SHFT 22
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_MASK 0x00200000                // cbinfra_ulposc_156M_req[21]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_req_SHFT 21
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_MASK 0x00100000                // cbinfra_ulposc_52M_req[20]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_req_SHFT 20
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_MASK 0x00080000                // cbinfra_ulposc_26M_req[19]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_req_SHFT 19
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_MASK 0x00040000                // connsys_ulposc_156M_req[18]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_req_SHFT 18
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_MASK 0x00020000                // connsys_ulposc_52M_req[17]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_req_SHFT 17
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_ADDR   CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_MASK   0x00010000                // lvts_ulposc_26M_req[16]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_req_SHFT   16
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_MASK 0x00008000                // topaon_ulposc_52M_req[15]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_req_SHFT 15
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_spmi_pmif_52M_rdy_ADDR     CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_spmi_pmif_52M_rdy_MASK     0x00000100                // spmi_pmif_52M_rdy[8]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_spmi_pmif_52M_rdy_SHFT     8
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_rdy_MASK 0x00000080                // cbinfra_wpll_160M_rdy[7]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_wpll_160M_rdy_SHFT 7
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_MASK 0x00000040                // cbinfra_ulposc_156M_rdy[6]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_156M_rdy_SHFT 6
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_MASK 0x00000020                // cbinfra_ulposc_52M_rdy[5]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_52M_rdy_SHFT 5
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_MASK 0x00000010                // cbinfra_ulposc_26M_rdy[4]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_cbinfra_ulposc_26M_rdy_SHFT 4
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_MASK 0x00000008                // connsys_ulposc_156M_rdy[3]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_156M_rdy_SHFT 3
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_MASK 0x00000004                // connsys_ulposc_52M_rdy[2]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_connsys_ulposc_52M_rdy_SHFT 2
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_ADDR   CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_MASK   0x00000002                // lvts_ulposc_26M_rdy[1]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_lvts_ulposc_26M_rdy_SHFT   1
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_3_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_MASK 0x00000001                // topaon_ulposc_52M_rdy[0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_3_topaon_ulposc_52M_rdy_SHFT 0

/* =====================================================================================

  ---CBTOP_ULPOSC_4 (0x70000000 + 0x250)---

    rg_re_cali_sw_trigger[0]     - (RW)  xxx 
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_rg_re_cali_sw_trigger_ADDR CB_CKGEN_TOP_CBTOP_ULPOSC_4_ADDR
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_rg_re_cali_sw_trigger_MASK 0x00000001                // rg_re_cali_sw_trigger[0]
#define CB_CKGEN_TOP_CBTOP_ULPOSC_4_rg_re_cali_sw_trigger_SHFT 0

/* =====================================================================================

  ---CBTOP_XTAL_DEBUG_0 (0x70000000 + 0x254)---

    rg_debug_sw_ctl[0]           - (RW)  xxx 
    RESERVED1[3..1]              - (RO) Reserved bits
    rg_debug_freq_offset_value[27..4] - (RW)  xxx 
    rg_debug_tri_cal[28]         - (RW)  xxx 
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_tri_cal_ADDR  CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_tri_cal_MASK  0x10000000                // rg_debug_tri_cal[28]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_tri_cal_SHFT  28
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_freq_offset_value_ADDR CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_freq_offset_value_MASK 0x0FFFFFF0                // rg_debug_freq_offset_value[27..4]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_freq_offset_value_SHFT 4
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_sw_ctl_ADDR   CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_sw_ctl_MASK   0x00000001                // rg_debug_sw_ctl[0]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_0_rg_debug_sw_ctl_SHFT   0

/* =====================================================================================

  ---CBTOP_XTAL_DEBUG_1 (0x70000000 + 0x258)---

    debug_cal_cnt[27..0]         - (RO)  xxx 
    xtal_valid_flag[28]          - (RO)  xxx 
    RESERVED29[31..29]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_xtal_valid_flag_ADDR   CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_xtal_valid_flag_MASK   0x10000000                // xtal_valid_flag[28]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_xtal_valid_flag_SHFT   28
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_debug_cal_cnt_ADDR     CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_debug_cal_cnt_MASK     0x0FFFFFFF                // debug_cal_cnt[27..0]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_1_debug_cal_cnt_SHFT     0

/* =====================================================================================

  ---CBTOP_XTAL_DEBUG_2 (0x70000000 + 0x25C)---

    rg_debug_target_value[27..0] - (RW)  xxx 
    RESERVED28[31..28]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_2_rg_debug_target_value_ADDR CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_2_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_2_rg_debug_target_value_MASK 0x0FFFFFFF                // rg_debug_target_value[27..0]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_2_rg_debug_target_value_SHFT 0

/* =====================================================================================

  ---CBTOP_XTAL_DEBUG_3 (0x70000000 + 0x260)---

    rg_debug_load_cnt[17..0]     - (RW)  xxx 
    RESERVED18[31..18]           - (RO) Reserved bits

 =====================================================================================*/
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_3_rg_debug_load_cnt_ADDR CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_3_ADDR
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_3_rg_debug_load_cnt_MASK 0x0003FFFF                // rg_debug_load_cnt[17..0]
#define CB_CKGEN_TOP_CBTOP_XTAL_DEBUG_3_rg_debug_load_cnt_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CB_CKGEN_TOP_REGS_H__
