/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __VLP_UDS_CTRL_REGS_H__
#define __VLP_UDS_CTRL_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define VLP_UDS_CTRL_BASE \
	0x70003000

#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR \
	(VLP_UDS_CTRL_BASE + 0x304)


#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_MASK \
	0x80000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_OSC_CALI_sw_SHFT \
	31
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_MASK \
	0x1F000000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div1_num_SHFT \
	24
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_MASK \
	0x001F0000
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_div2_num_SHFT \
	16
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_ADDR \
	VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_ADDR
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_MASK \
	0x0000FFFF
#define VLP_UDS_CTRL_CBTOP_ULPOSC_CTRL1_RG_k_target_value_SHFT \
	0

#ifdef __cplusplus
}
#endif

#endif
